version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "6464:6464"
    environment:
      - PORT=6464   
    volumes:
      - ./server:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
