version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "50001:5000"
    volumes:
      - ./server:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
